name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  GCP_SA_KEY: ${{ secrets.RUN_SA_KEY }}
  RUN_REGION: us-central1
  SERVICE_NAME: cssbattle-api
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  PORT: ${{ secrets.PORT }}
  SOCKET_PORT: ${{ secrets.SOCKET_PORT }}
  SECRET: ${{ secrets.SECRET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.RUN_PROJECT }}
        service_account_key: ${{ env.GCP_SA_KEY }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA"

    # Deploy image to Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.2.0
      with:
        service: ${{ env.SERVICE_NAME }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}
        region: ${{ env.RUN_REGION }}
        credentials: ${{ env.GCP_SA_KEY }}
        env_vars: "MYSQL_HOST=${{ env.MYSQL_HOST }},MYSQL_USER=${{ envMYSQL_USER }}"
