name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  GCP_SA_KEY: ${{ secrets.RUN_SA_KEY }}
  RUN_REGION: us-central1
  SERVICE_NAME: cssbattle-api
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  PORT: ${{ secrets.PORT }}
  SOCKET_PORT: ${{ secrets.SOCKET_PORT }}
  SECRET: ${{ secrets.SECRET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.RUN_PROJECT }}
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        export_default_credentials: true

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

    # Build and push image to Google Container Registry
    - name: Deploy
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --update-env-vars MYSQL_HOST=$MYSQL_HOST,MYSQL_USER=$MYSQL_USER,MYSQL_PASS=$MYSQL_PASS,MYSQL_DATABASE=$MYSQL_DATABASE,PORT=$PORT,SOCKET_PORT=$SOCKET_PORT,SECRET=$SECRET
